name: context variable demo
on: workflow_dispatch
jobs:
  context_demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: action/checkout@v7.0.1
      - name: who am I
        run: |
          echo "This is triggered by ${{ github.actor}}"

