name: functions_demo
on: push
jobs:
  functionsDemo:
    runs-on: ubuntu-latest
    steps:
      - name: functions to use in workflow
        if: contains(github.ref_name, 'master')
        run: |
          echo "Running this workflow using Branch ${{ github.ref_name }}"
          exit 1
  Success_notify:
    runs-on: ubuntu-latest
    needs: functionsDemo
#    if: success()
    if: always() && needs.functionsDemo.result == 'success'
    steps:
      - name: Job is successfull
        run: echo "Sending success notification"
  Failure_notify:
    runs-on: ubuntu-latest
    needs: ['functionsDemo']
    if: always() && needs.functionsDemo.result == 'failure'
    steps:
      - name: Job is Failed
        run: echo "Sending Failure notification"
