name: if_Demo
on:
  push:
    branches:
      - main
      - master
jobs:
  if_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Fist condition
        if: github.ref == "refs/heads/master"
        run: echo "Running on master branch"
#        default: echo "Running on other Branch"