name: if_Demo
on: workflow_dispatch
#  push:
#    branches:
#      - main
#      - master
jobs:
  if_demo:
    runs-on: ubuntu-latest
    steps:
      - name: First condition
        if: github.ref_name == 'master'
        run: echo "Running on master branch"
#        default: echo "Running on other Branch"