name: or_demo
on: push
jobs:
  or_demo:
    runs-on: ubuntu-latest
    steps:
      - name: First condition
        if: github.actor == 'harshith010' || 'shetty010'
        run: echo "Triggered by ${{ github.actor }}"
#        default: echo "Running on other Branch"